from pathlib import Path
p=Path('mobile/src/editor/PhotoEditorScreen.tsx')
s=p.read_text()
def r(a,b):
    global s
    if a not in s: raise SystemExit('anchor missing: '+a[:70])
    s=s.replace(a,b,1)
r("const EFFECTS:{name:string;filter:FilterName}[]=[\n  {name:'Vignette',filter:'dramatic'},{name:'Grain',filter:'vintage'},{name:'Glow',filter:'chrome'},\n  {name:'Bleach',filter:'fade'},{name:'Light Leak',filter:'warm'},{name:'Mono',filter:'noir'},\n];","const EFFECTS:{name:string;filter:FilterName}[]=[\n  {name:'Dramatic',filter:'dramatic'},{name:'Vintage',filter:'vintage'},{name:'Chrome',filter:'chrome'},\n  {name:'Fade',filter:'fade'},{name:'Warm',filter:'warm'},{name:'Noir',filter:'noir'},\n];")
r("  async function bakeVisuals(){\n    if(!workingUri)return;\n    const hasCustom=!sameAdjust(adjust,DEFAULT_ADJUST);\n    if(filter==='custom'&&!hasCustom)return;\n    const result=await applyFilter({sourceUri:workingUri,filter,intensity,customParams:filter==='custom'?customParams:undefined,returnFormat:'uri',quality:100});\n    if(!result.uri)throw new Error('Không thể kết xuất bước chỉnh hiện tại.');\n    setWorkingUri(result.uri);setSize({width:result.width,height:result.height});setFilter('custom');setIntensity(1);setAdjust(DEFAULT_ADJUST);\n  }","  async function bakeVisuals():Promise<{uri:string;width:number;height:number}>{\n    if(!workingUri)throw new Error('Không có ảnh đang chỉnh.');\n    const hasCustom=!sameAdjust(adjust,DEFAULT_ADJUST);\n    if(filter==='custom'&&!hasCustom)return {uri:workingUri,width:size.width,height:size.height};\n    const result=await applyFilter({sourceUri:workingUri,filter,intensity,customParams:filter==='custom'?customParams:undefined,returnFormat:'uri',quality:100});\n    if(!result.uri)throw new Error('Không thể kết xuất bước chỉnh hiện tại.');\n    setWorkingUri(result.uri);setSize({width:result.width,height:result.height});setFilter('custom');setIntensity(1);setAdjust(DEFAULT_ADJUST);\n    return {uri:result.uri,width:result.width,height:result.height};\n  }")
r("async function applyCropNow(){if(!workingUri||!cropRect)return;const before=snapshot();setBusy(true);try{await bakeVisuals();const source=workingUri;const result=await cropImage({sourceUri:source,cropRect,returnFormat:'uri',quality:100});","async function applyCropNow(){if(!workingUri||!cropRect)return;const before=snapshot();setBusy(true);try{const baked=await bakeVisuals();const result=await cropImage({sourceUri:baked.uri,cropRect,returnFormat:'uri',quality:100});")
r("async function rotate(degrees:90|180|270){if(!workingUri)return;const before=snapshot();setBusy(true);try{await bakeVisuals();const result=await rotateImage({sourceUri:workingUri,degrees,expand:true,returnFormat:'uri',quality:100});","async function rotate(degrees:90|180|270){if(!workingUri)return;const before=snapshot();setBusy(true);try{const baked=await bakeVisuals();const result=await rotateImage({sourceUri:baked.uri,degrees,expand:true,returnFormat:'uri',quality:100});")
r("async function flip(axis:'horizontal'|'vertical'){if(!workingUri)return;const before=snapshot();setBusy(true);try{await bakeVisuals();const result=await ImageManipulator.manipulateAsync(workingUri,[{flip:axis==='horizontal'?ImageManipulator.FlipType.Horizontal:ImageManipulator.FlipType.Vertical}],","async function flip(axis:'horizontal'|'vertical'){if(!workingUri)return;const before=snapshot();setBusy(true);try{const baked=await bakeVisuals();const result=await ImageManipulator.manipulateAsync(baked.uri,[{flip:axis==='horizontal'?ImageManipulator.FlipType.Horizontal:ImageManipulator.FlipType.Vertical}],")
r("async function straightenNow(){if(!workingUri||Math.abs(straighten)<.05)return;const before=snapshot();setBusy(true);try{await bakeVisuals();const result=await rotateImage({sourceUri:workingUri,degrees:straighten,expand:true,returnFormat:'uri',quality:100});","async function straightenNow(){if(!workingUri||Math.abs(straighten)<.05)return;const before=snapshot();setBusy(true);try{const baked=await bakeVisuals();const result=await rotateImage({sourceUri:baked.uri,degrees:straighten,expand:true,returnFormat:'uri',quality:100});")
p.write_text(s)
