from pathlib import Path
p=Path('docs/V4_SAAS_PLAN.md')
s=p.read_text()
s=s.replace("- [ ] Instantiate/migrate the default legacy workspace from Desktop startup.\n- [ ] Add workspace-aware pairing credential implementation in Desktop.\n- [ ] Persist workspace context on Mobile after pairing/login.\n- [ ] Enforce media ingest quota before upload acceptance.\n- [ ] Scope media/provider index operations by workspace.\n", "- [x] Instantiate/migrate the default legacy workspace from Desktop startup and register the desktop device.\n- [ ] Add workspace-aware pairing credential implementation in Desktop.\n- [ ] Persist workspace context on Mobile after pairing/login.\n- [x] Enforce media ingest quota before upload acceptance using declared bytes, atomic SQLite reservation, size verification and rollback.\n- [x] Keep workspace managed-storage/provider usage consistent on media delete and Google Drive connect/disconnect, with durable audit events.\n- [ ] Scope media/provider index operations by workspace.\n")
s=s.replace("1. Instantiate `SqliteWorkspaceRepository` in Desktop startup and create/migrate the legacy personal workspace deterministically.\n2. Put workspace ID + desktop device ID + short-lived challenge/capability metadata into the pairing flow.\n3. Persist returned workspace identity and session material in Mobile SecureStore.\n4. Add authoritative WorkspaceUsage byte reservation/check before `/api/v1/media` accepts a write; roll back reservations on failed ingest.\n5. Add `workspace_id` to media/provider catalog rows with safe migration and prove cross-workspace reads/writes are rejected.\n6. Replace static Web edge bootstrap role/workspace configuration with verified SaaS access tokens and emit durable audit events for mutations.\n", "1. Put workspace ID + desktop device ID + short-lived challenge/capability metadata into the pairing flow.\n2. Persist returned workspace identity and session material in Mobile SecureStore and stop treating pair-code as the long-lived authorization secret.\n3. Add `workspace_id` to media/provider catalog rows with backward-safe migration and prove cross-workspace reads/writes are rejected.\n4. Add a monthly usage period/reset model so `monthlyIngressBytes` is authoritative across month boundaries.\n5. Replace static Web edge bootstrap role/workspace configuration with verified SaaS access tokens and extend durable audit emission to all administrative mutations.\n6. Add workspace/plan/usage APIs and surface real quota state in the shared Desktop/Web UI and Mobile.\n")
needle="Media bytes should continue to use the most efficient available data-plane route.\n"
addition="""\n### Phase B1 — legacy edge bootstrap and write quota enforcement (implemented)\n\nDesktop now creates the legacy personal workspace deterministically at startup, registers itself as a workspace device, and reconstructs managed storage/provider usage from existing state. Mobile sends the materialized file byte size before upload. Desktop reserves managed-storage and monthly-ingress bytes atomically before consuming the body, rejects over-quota writes, verifies the received byte count, rolls the reservation back on failed ingest, and records successful ingest in the workspace audit log. Media deletion releases managed storage but intentionally retains monthly ingress for the current accounting period. Google Drive connect/disconnect updates provider usage and durable audit state.\n\nThe remaining accounting gap is period rollover for monthly ingress; until implemented, the counter is cumulative rather than calendar-month authoritative.\n"""
if addition.strip() not in s:
    s=s.replace(needle,needle+addition,1)
p.write_text(s)
