from pathlib import Path

workspace = Path('packages/persistence-sqlite/src/workspace.ts')
text = workspace.read_text()
needle = """  getUsage(workspaceId: string): WorkspaceUsage {\n    const row = this.store.db.prepare('SELECT * FROM photox_workspace_usage WHERE workspace_id=?').get(workspaceId) as Record<string, unknown> | undefined;\n    if (!row) return { ...ZERO_USAGE };\n    return {\n      managedStorageBytes: Number(row.managed_storage_bytes), monthlyIngressBytes: Number(row.monthly_ingress_bytes), members: Number(row.members),\n      devices: Number(row.devices), storageProviders: Number(row.storage_providers), publicShares: Number(row.public_shares),\n    };\n  }\n"""
replacement = needle + """
\n  reserveMediaWrite(workspaceId: string, bytes: number, limits: { maxManagedStorageBytes: number | null; maxMonthlyIngressBytes: number | null }): WorkspaceUsage {\n    if (!Number.isFinite(bytes) || bytes <= 0) throw new Error('INVALID_MEDIA_RESERVATION_BYTES');\n    this.store.db.exec('BEGIN IMMEDIATE');\n    try {\n      const usage = this.getUsage(workspaceId);\n      const nextManaged = usage.managedStorageBytes + bytes;\n      const nextIngress = usage.monthlyIngressBytes + bytes;\n      if (limits.maxManagedStorageBytes !== null && nextManaged > limits.maxManagedStorageBytes) throw new Error('WORKSPACE_MANAGED_STORAGE_QUOTA_EXCEEDED');\n      if (limits.maxMonthlyIngressBytes !== null && nextIngress > limits.maxMonthlyIngressBytes) throw new Error('WORKSPACE_MONTHLY_INGRESS_QUOTA_EXCEEDED');\n      const next = { ...usage, managedStorageBytes: nextManaged, monthlyIngressBytes: nextIngress };\n      this.setUsage(workspaceId, next);\n      this.store.db.exec('COMMIT');\n      return next;\n    } catch (error) {\n      this.store.db.exec('ROLLBACK');\n      throw error;\n    }\n  }\n\n  releaseMediaReservation(workspaceId: string, bytes: number, options: { releaseManaged?: boolean; releaseIngress?: boolean } = { releaseManaged: true, releaseIngress: true }): WorkspaceUsage {\n    if (!Number.isFinite(bytes) || bytes <= 0) throw new Error('INVALID_MEDIA_RESERVATION_BYTES');\n    this.store.db.exec('BEGIN IMMEDIATE');\n    try {\n      const usage = this.getUsage(workspaceId);\n      const next = {\n        ...usage,\n        managedStorageBytes: options.releaseManaged === false ? usage.managedStorageBytes : Math.max(0, usage.managedStorageBytes - bytes),\n        monthlyIngressBytes: options.releaseIngress === false ? usage.monthlyIngressBytes : Math.max(0, usage.monthlyIngressBytes - bytes),\n      };\n      this.setUsage(workspaceId, next);\n      this.store.db.exec('COMMIT');\n      return next;\n    } catch (error) {\n      this.store.db.exec('ROLLBACK');\n      throw error;\n    }\n  }\n"""
if needle not in text:
    raise SystemExit('workspace getUsage needle not found')
workspace.write_text(text.replace(needle, replacement, 1))

test = Path('packages/persistence-sqlite/src/workspace.test.ts')
t = test.read_text()
insert = """
\n  it('atomically reserves media bytes and rolls back rejected quota writes', () => {\n    const { store, repo } = setup();\n    repo.ensureLegacyPersonalWorkspace({ workspaceId: 'ws-a', ownerUserId: 'user-a' });\n    repo.setUsage('ws-a', { managedStorageBytes: 100, monthlyIngressBytes: 200, members: 1, devices: 1, storageProviders: 0, publicShares: 0 });\n    expect(repo.reserveMediaWrite('ws-a', 50, { maxManagedStorageBytes: 200, maxMonthlyIngressBytes: 300 })).toMatchObject({ managedStorageBytes: 150, monthlyIngressBytes: 250 });\n    expect(() => repo.reserveMediaWrite('ws-a', 60, { maxManagedStorageBytes: 200, maxMonthlyIngressBytes: 300 })).toThrow('WORKSPACE_MANAGED_STORAGE_QUOTA_EXCEEDED');\n    expect(repo.getUsage('ws-a')).toMatchObject({ managedStorageBytes: 150, monthlyIngressBytes: 250 });\n    expect(repo.releaseMediaReservation('ws-a', 50)).toMatchObject({ managedStorageBytes: 100, monthlyIngressBytes: 200 });\n    store.close();\n  });\n"""
marker = "\n  it('preserves workspace identity across refresh sessions'"
if marker not in t:
    raise SystemExit('workspace test marker not found')
test.write_text(t.replace(marker, insert + marker, 1))

mobile = Path('mobile/src/sync/mobileSync.ts')
m = mobile.read_text()
header_needle = """            'x-photosync-media-type': asset.mediaType,\n"""
if header_needle not in m:
    raise SystemExit('mobile header needle not found')
mobile.write_text(m.replace(header_needle, header_needle + "            'x-photosync-size': String(local!.size),\n", 1))

main = Path('desktop/electron/main.ts')
s = main.read_text()
s = s.replace("import { chooseAccount, evaluateBackupHealth, DEFAULT_PHOTO_POLICY, DEFAULT_VIDEO_POLICY, type MediaReplica, type StorageAccount } from '@photosync/core';", "import { chooseAccount, entitlementsForPlan, evaluateBackupHealth, DEFAULT_PHOTO_POLICY, DEFAULT_VIDEO_POLICY, type MediaReplica, type StorageAccount } from '@photosync/core';")
s = s.replace("import { SqlitePhotoXStore, SqliteGooglePhotosMigrationLedger } from '@photox/persistence-sqlite';", "import { SqlitePhotoXStore, SqliteGooglePhotosMigrationLedger, SqliteWorkspaceRepository } from '@photox/persistence-sqlite';")
s = s.replace("let migrationStore:SqlitePhotoXStore|null=null;\nlet migrationService", "let migrationStore:SqlitePhotoXStore|null=null;\nlet workspaceRepository:SqliteWorkspaceRepository|null=null;\nlet migrationService")
anchor = "function notifyRenderer(channel:string,payload:unknown){"
helper = """const LEGACY_WORKSPACE_ID=process.env.PHOTOX_WORKSPACE_ID||'legacy-personal';\nconst LEGACY_OWNER_USER_ID=process.env.PHOTOX_OWNER_USER_ID||'legacy-owner';\nconst LEGACY_DESKTOP_DEVICE_ID=`desktop_${crypto.createHash('sha256').update(os.hostname()).digest('hex').slice(0,20)}`;\n\nfunction requireWorkspaceRepository(){if(!workspaceRepository)throw new Error('WORKSPACE_REPOSITORY_NOT_READY');return workspaceRepository;}\n\nasync function bootstrapLegacyWorkspace(){\n  const repo=requireWorkspaceRepository();\n  const result=repo.ensureLegacyPersonalWorkspace({workspaceId:LEGACY_WORKSPACE_ID,ownerUserId:LEGACY_OWNER_USER_ID,name:process.env.PHOTOX_WORKSPACE_NAME||'My PhotoX',plan:'personal'});\n  repo.putDevice({id:LEGACY_DESKTOP_DEVICE_ID,workspaceId:LEGACY_WORKSPACE_ID,userId:LEGACY_OWNER_USER_ID,name:os.hostname(),platform:process.platform==='darwin'?'macos':process.platform==='win32'?'windows':process.platform==='linux'?'linux':'unknown',kind:'desktop',createdAt:Date.now(),lastSeenAt:Date.now()});\n  const current=repo.getUsage(LEGACY_WORKSPACE_ID);\n  const rows=await readIndex();\n  const managedStorageBytes=rows.reduce((sum,row)=>sum+Math.max(0,row.size||0),0);\n  repo.setUsage(LEGACY_WORKSPACE_ID,{...current,managedStorageBytes,members:repo.listMemberships(LEGACY_WORKSPACE_ID).filter(item=>item.status==='active').length,devices:repo.listDevices(LEGACY_WORKSPACE_ID).filter(item=>!item.revokedAt).length,storageProviders:(await savedDriveAccounts()).length});\n  if(result.created)repo.appendAudit({workspaceId:LEGACY_WORKSPACE_ID,actorUserId:LEGACY_OWNER_USER_ID,actorDeviceId:LEGACY_DESKTOP_DEVICE_ID,action:'workspace.legacy_bootstrap',targetType:'workspace',targetId:LEGACY_WORKSPACE_ID});\n}\n\n"""
if anchor not in s: raise SystemExit('main notify anchor not found')
s = s.replace(anchor, helper + anchor, 1)
old_receive = """  const filename=safeFilename(decodeURIComponent(String(req.headers['x-photosync-filename']||`media-${Date.now()}`))); const createdAt=Number(req.headers['x-photosync-created-at']||Date.now());\n  const declaredMediaType=String(req.headers['x-photosync-media-type']||'photo')==='video'?'video':'photo';\n"""
new_receive = """  const filename=safeFilename(decodeURIComponent(String(req.headers['x-photosync-filename']||`media-${Date.now()}`))); const createdAt=Number(req.headers['x-photosync-created-at']||Date.now());\n  const declaredSize=Number(req.headers['x-photosync-size']||req.headers['content-length']||0);\n  if(!Number.isFinite(declaredSize)||declaredSize<=0){res.writeHead(411,{'content-type':'application/json'});res.end(JSON.stringify({error:'MEDIA_SIZE_REQUIRED'}));return;}\n  const repo=requireWorkspaceRepository();const workspace=repo.getWorkspace(LEGACY_WORKSPACE_ID);if(!workspace){res.writeHead(503);res.end('Workspace unavailable');return;}\n  const entitlements=entitlementsForPlan(workspace.plan);\n  try{repo.reserveMediaWrite(LEGACY_WORKSPACE_ID,declaredSize,{maxManagedStorageBytes:entitlements.maxManagedStorageBytes,maxMonthlyIngressBytes:entitlements.maxMonthlyIngressBytes});}\n  catch(error){const message=error instanceof Error?error.message:String(error);res.writeHead(413,{'content-type':'application/json'});res.end(JSON.stringify({error:message}));return;}\n  let reservationCommitted=false;\n  const declaredMediaType=String(req.headers['x-photosync-media-type']||'photo')==='video'?'video':'photo';\n"""
if old_receive not in s: raise SystemExit('receive preflight needle not found')
s=s.replace(old_receive,new_receive,1)
old_pipeline = """  await fs.mkdir(incomingDir(),{recursive:true});await fs.mkdir(folder,{recursive:true}); const tmp=path.join(incomingDir(),`${crypto.randomUUID()}.part`); await pipeline(req,createWriteStream(tmp));\n  const stat=await fs.stat(tmp); const hash=await hashFile(tmp); let target=path.join(folder,filename);"""
new_pipeline = """  await fs.mkdir(incomingDir(),{recursive:true});await fs.mkdir(folder,{recursive:true}); const tmp=path.join(incomingDir(),`${crypto.randomUUID()}.part`);\n  try{\n    await pipeline(req,createWriteStream(tmp));\n    const stat=await fs.stat(tmp);\n    if(stat.size!==declaredSize)throw new Error(`MEDIA_SIZE_MISMATCH:${declaredSize}:${stat.size}`);\n    const hash=await hashFile(tmp); let target=path.join(folder,filename);"""
if old_pipeline not in s: raise SystemExit('pipeline needle not found')
s=s.replace(old_pipeline,new_pipeline,1)
old_tail = """  if(declaredMediaType==='video')void processVideoRow(key);void enqueueCloudUpload(row);\n}\n\nasync function desktopStatus"""
new_tail = """  reservationCommitted=true;\n  repo.appendAudit({workspaceId:LEGACY_WORKSPACE_ID,actorUserId:LEGACY_OWNER_USER_ID,actorDeviceId:deviceId,action:'media.ingest',targetType:'media',targetId:key,metadata:{filename,size:stat.size}});\n  if(declaredMediaType==='video')void processVideoRow(key);void enqueueCloudUpload(row);\n  }catch(error){\n    await fs.unlink(tmp).catch(()=>undefined);\n    if(!reservationCommitted)repo.releaseMediaReservation(LEGACY_WORKSPACE_ID,declaredSize);\n    throw error;\n  }\n}\n\nasync function desktopStatus"""
if old_tail not in s: raise SystemExit('receive tail needle not found')
s=s.replace(old_tail,new_tail,1)
startup_old = """migrationStore=new SqlitePhotoXStore({path:migrationDbFile()});migrationService=new DesktopGooglePhotosMigrationService({accountsDir:googlePhotosAccountsDir(),workspaceId:process.env.PHOTOX_WORKSPACE_ID||'legacy-personal'"""
startup_new = """migrationStore=new SqlitePhotoXStore({path:migrationDbFile()});workspaceRepository=new SqliteWorkspaceRepository(migrationStore);await bootstrapLegacyWorkspace();migrationService=new DesktopGooglePhotosMigrationService({accountsDir:googlePhotosAccountsDir(),workspaceId:LEGACY_WORKSPACE_ID"""
if startup_old not in s: raise SystemExit('startup needle not found')
s=s.replace(startup_old,startup_new,1)
s=s.replace("migrationStore?.close();migrationStore=null;migrationService=null", "migrationStore?.close();migrationStore=null;workspaceRepository=null;migrationService=null")
main.write_text(s)
