from pathlib import Path

p=Path('desktop/electron/main.ts')
s=p.read_text()
s=s.replace("import { isVideoFilename, mimeTypeForFilename, processVideoFile } from './mediaProcessing.js';", "import { isVideoFilename, mimeTypeForFilename, processVideoFile } from './mediaProcessing.js';\nimport { SqlitePhotoXStore, SqliteGooglePhotosMigrationLedger } from '@photox/persistence-sqlite';\nimport { DesktopGooglePhotosMigrationService } from './googlePhotosMigration.js';")
s=s.replace("let repairSweepTimer:NodeJS.Timeout|null=null;", "let repairSweepTimer:NodeJS.Timeout|null=null;\nlet migrationStore:SqlitePhotoXStore|null=null;\nlet migrationService:DesktopGooglePhotosMigrationService|null=null;")
s=s.replace("function driveAccountsDir(){ return path.join(stateDir(),'google-accounts'); }", "function driveAccountsDir(){ return path.join(stateDir(),'google-accounts'); }\nfunction googlePhotosAccountsDir(){ return path.join(stateDir(),'google-photos-accounts'); }\nfunction migrationDbFile(){ return path.join(stateDir(),'migration.sqlite'); }")
s=s.replace("function oauthClient(){", "function oauthClient(redirectUri=REDIRECT_URI){")
s=s.replace("return new OAuth2Client(id,secret,REDIRECT_URI);", "return new OAuth2Client(id,secret,redirectUri);")
insert="""
async function uploadMigrationItemToDrive(input:{accountId:string;source:any;response:Response;signal?:AbortSignal;onBytes?:(bytes:number)=>void}){
  const account=(await runtimeDriveAccounts()).find(item=>item.id===input.accountId);if(!account)throw new Error('GOOGLE_DRIVE_DESTINATION_NOT_FOUND');
  const token=await account.client.getAccessToken();if(!token.token)throw new Error('GOOGLE_DRIVE_ACCESS_TOKEN_MISSING');
  const bytes=Buffer.from(await input.response.arrayBuffer());if(input.signal?.aborted)throw new Error('MIGRATION_ABORTED');
  const mimeType=input.source.mediaFile?.mimeType||'application/octet-stream';const filename=safeFilename(input.source.mediaFile?.filename||`google-photo-${Date.now()}`);
  const session=await createResumableUploadSession(token.token,{name:filename,mimeType,sizeBytes:bytes.byteLength,folderId:account.folderId,appProperties:{photoxMigration:'true',sourceMediaId:String(input.source.id)}});
  const uploaded=await net.fetch(session,{method:'PUT',headers:{'content-type':mimeType,'content-length':String(bytes.byteLength)},body:bytes});
  if(!uploaded.ok)throw new Error(`Drive migration upload ${uploaded.status}: ${await uploaded.text()}`);input.onBytes?.(bytes.byteLength);
  const result=await uploaded.json() as {id?:string;webViewLink?:string};if(!result.id)throw new Error('GOOGLE_DRIVE_DESTINATION_ID_MISSING');
  return {targetId:result.id,targetUrl:result.webViewLink};
}
function requireMigrationService(){if(!migrationService)throw new Error('MIGRATION_SERVICE_NOT_READY');return migrationService;}
"""
s=s.replace("function enqueueCloudUpload(row:MediaIndexRow){", insert+"\nfunction enqueueCloudUpload(row:MediaIndexRow){")
ipc="""
ipcMain.handle('photosync:google-photos-accounts',()=>requireMigrationService().listAccounts());
ipcMain.handle('photosync:google-photos-connect',(_event,capability:'picker'|'append')=>requireMigrationService().connectAccount(capability));
ipcMain.handle('photosync:google-photos-remove',(_event,accountId:string)=>requireMigrationService().removeAccount(accountId));
ipcMain.handle('photosync:migration-list',()=>requireMigrationService().listJobs());
ipcMain.handle('photosync:migration-snapshot',(_event,jobId:string)=>requireMigrationService().getSnapshot(jobId));
ipcMain.handle('photosync:migration-create',(_event,input:any)=>requireMigrationService().createSelection(input));
ipcMain.handle('photosync:migration-materialize',(_event,jobId:string)=>requireMigrationService().materializeSelection(jobId));
ipcMain.handle('photosync:migration-run',(_event,jobId:string)=>requireMigrationService().run(jobId));
ipcMain.handle('photosync:migration-pause',(_event,jobId:string)=>{requireMigrationService().pause(jobId);return requireMigrationService().getSnapshot(jobId)});
ipcMain.handle('photosync:migration-resume',(_event,jobId:string)=>requireMigrationService().resume(jobId));
ipcMain.handle('photosync:migration-cancel',(_event,jobId:string)=>{requireMigrationService().cancel(jobId);return requireMigrationService().getSnapshot(jobId)});
ipcMain.handle('photosync:migration-retry',(_event,jobId:string)=>requireMigrationService().retryFailed(jobId));
"""
s=s.replace("ipcMain.handle('photosync:retry-cloud',async()=>{await retryQueuedCloud();return desktopStatus()});", "ipcMain.handle('photosync:retry-cloud',async()=>{await retryQueuedCloud();return desktopStatus()});\n"+ipc)
old="app.whenReady().then(async()=>{await fs.mkdir(libraryDir(),{recursive:true});await fs.mkdir(videoCacheDir(),{recursive:true});await startReceiver();"
new="app.whenReady().then(async()=>{await fs.mkdir(libraryDir(),{recursive:true});await fs.mkdir(videoCacheDir(),{recursive:true});await fs.mkdir(googlePhotosAccountsDir(),{recursive:true});migrationStore=new SqlitePhotoXStore({path:migrationDbFile()});migrationService=new DesktopGooglePhotosMigrationService({accountsDir:googlePhotosAccountsDir(),workspaceId:process.env.PHOTOX_WORKSPACE_ID||'legacy-personal',oauthClient,openExternal:url=>shell.openExternal(url),ledger:new SqliteGooglePhotosMigrationLedger(migrationStore),uploadToDrive:uploadMigrationItemToDrive,onUpdated:snapshot=>notifyRenderer('photosync:migration-updated',snapshot)});await startReceiver();"
s=s.replace(old,new)
s=s.replace("app.on('before-quit',()=>{if(repairSweepTimer)clearInterval(repairSweepTimer);repairSweepTimer=null;stopCloudflareTunnelSupervisor()});", "app.on('before-quit',()=>{if(repairSweepTimer)clearInterval(repairSweepTimer);repairSweepTimer=null;stopCloudflareTunnelSupervisor();migrationStore?.close();migrationStore=null;migrationService=null});")
if s==p.read_text(): raise SystemExit('no main.ts changes applied')
p.write_text(s)

p=Path('desktop/electron/preload.cts');s=p.read_text()
s=s.replace("  retryCloud: () => ipcRenderer.invoke('photosync:retry-cloud'),", "  retryCloud: () => ipcRenderer.invoke('photosync:retry-cloud'),\n  listGooglePhotosAccounts: () => ipcRenderer.invoke('photosync:google-photos-accounts'),\n  connectGooglePhotosAccount: (capability: 'picker'|'append') => ipcRenderer.invoke('photosync:google-photos-connect', capability),\n  removeGooglePhotosAccount: (accountId: string) => ipcRenderer.invoke('photosync:google-photos-remove', accountId),\n  listMigrations: () => ipcRenderer.invoke('photosync:migration-list'),\n  getMigration: (jobId: string) => ipcRenderer.invoke('photosync:migration-snapshot', jobId),\n  createMigration: (input: unknown) => ipcRenderer.invoke('photosync:migration-create', input),\n  materializeMigration: (jobId: string) => ipcRenderer.invoke('photosync:migration-materialize', jobId),\n  runMigration: (jobId: string) => ipcRenderer.invoke('photosync:migration-run', jobId),\n  pauseMigration: (jobId: string) => ipcRenderer.invoke('photosync:migration-pause', jobId),\n  resumeMigration: (jobId: string) => ipcRenderer.invoke('photosync:migration-resume', jobId),\n  cancelMigration: (jobId: string) => ipcRenderer.invoke('photosync:migration-cancel', jobId),\n  retryMigration: (jobId: string) => ipcRenderer.invoke('photosync:migration-retry', jobId),")
s=s.replace("  onTunnelState: (callback: (event: unknown) => void) => {", "  onMigrationUpdated: (callback: (event: unknown) => void) => {\n    const handler = (_event: Electron.IpcRendererEvent, payload: unknown) => callback(payload);\n    ipcRenderer.on('photosync:migration-updated', handler);\n    return () => ipcRenderer.removeListener('photosync:migration-updated', handler);\n  },\n  onTunnelState: (callback: (event: unknown) => void) => {")
p.write_text(s)

p=Path('desktop/src/bridge.ts');s=p.read_text()
s=s.replace("export type BackupHealthSnapshot", "export type GooglePhotosAccount={id:string;email:string;capabilities:('picker'|'append')[];status:'ready'|'unavailable'};\nexport type MigrationJob={id:string;workspaceId:string;sourceAccountId:string;sourcePickerSessionId?:string;target:'google_photos'|'google_drive';targetAccountId:string;state:string;totalItems:number;completedItems:number;failedItems:number;totalBytes?:number;transferredBytes:number;createdAt:string;updatedAt:string;startedAt?:string;completedAt?:string;lastError?:string};\nexport type MigrationItem={id:string;jobId:string;sourceMediaId:string;filename:string;mimeType?:string;sizeBytes?:number;state:string;attempts:number;transferredBytes:number;targetId?:string;targetUrl?:string;error?:string;createdAt:string;updatedAt:string};\nexport type MigrationSnapshot={job:MigrationJob;items:MigrationItem[]};\nexport type BackupHealthSnapshot")
s=s.replace("  retryCloud():Promise<DesktopStatus>;", "  retryCloud():Promise<DesktopStatus>;\n  listGooglePhotosAccounts():Promise<GooglePhotosAccount[]>;\n  connectGooglePhotosAccount(capability:'picker'|'append'):Promise<GooglePhotosAccount>;\n  removeGooglePhotosAccount(accountId:string):Promise<void>;\n  listMigrations():Promise<MigrationJob[]>;\n  getMigration(jobId:string):Promise<MigrationSnapshot>;\n  createMigration(input:{sourceAccountId:string;target:'google_photos'|'google_drive';targetAccountId:string;maxItemCount?:number}):Promise<{job:MigrationJob;pickerUri:string;expireTime?:string}>;\n  materializeMigration(jobId:string):Promise<MigrationSnapshot>;\n  runMigration(jobId:string):Promise<MigrationJob>;\n  pauseMigration(jobId:string):Promise<MigrationSnapshot>;\n  resumeMigration(jobId:string):Promise<MigrationJob>;\n  cancelMigration(jobId:string):Promise<MigrationSnapshot>;\n  retryMigration(jobId:string):Promise<MigrationJob>;\n  onMigrationUpdated(cb:(event:MigrationSnapshot)=>void):()=>void;")
s=s.replace("    retryCloud:()=>json('/api/web/v1/cloud/retry',{method:'POST'}),", "    retryCloud:()=>json('/api/web/v1/cloud/retry',{method:'POST'}),\n    listGooglePhotosAccounts:()=>json('/api/web/v1/google-photos/accounts'),\n    connectGooglePhotosAccount:(capability)=>json('/api/web/v1/google-photos/accounts/connect',{method:'POST',body:JSON.stringify({capability})}),\n    removeGooglePhotosAccount:async(accountId)=>{await json(`/api/web/v1/google-photos/accounts/${encodeURIComponent(accountId)}`,{method:'DELETE'});},\n    listMigrations:()=>json('/api/web/v1/migrations'),\n    getMigration:(jobId)=>json(`/api/web/v1/migrations/${encodeURIComponent(jobId)}`),\n    createMigration:(input)=>json('/api/web/v1/migrations',{method:'POST',body:JSON.stringify(input)}),\n    materializeMigration:(jobId)=>json(`/api/web/v1/migrations/${encodeURIComponent(jobId)}/selection`,{method:'POST'}),\n    runMigration:(jobId)=>json(`/api/web/v1/migrations/${encodeURIComponent(jobId)}/run`,{method:'POST'}),\n    pauseMigration:(jobId)=>json(`/api/web/v1/migrations/${encodeURIComponent(jobId)}/pause`,{method:'POST'}),\n    resumeMigration:(jobId)=>json(`/api/web/v1/migrations/${encodeURIComponent(jobId)}/resume`,{method:'POST'}),\n    cancelMigration:(jobId)=>json(`/api/web/v1/migrations/${encodeURIComponent(jobId)}/cancel`,{method:'POST'}),\n    retryMigration:(jobId)=>json(`/api/web/v1/migrations/${encodeURIComponent(jobId)}/retry`,{method:'POST'}),")
s=s.replace("    onFileReceived:(cb)=>subscribe('file-received',cb),", "    onMigrationUpdated:(cb)=>subscribe('migration-updated',cb),\n    onFileReceived:(cb)=>subscribe('file-received',cb),")
p.write_text(s)
