from pathlib import Path
p=Path('mobile/src/home/MobileHome.tsx')
s=p.read_text()
s=s.replace("import { SwipeMediaStage } from '../viewer/SwipeMediaStage';\n","import { SwipeMediaStage } from '../viewer/SwipeMediaStage';\nimport { PhotoTimeline } from './PhotoTimeline';\n")
old="  function renderGrid(items:DisplayAsset[],trashMode=false){return <View style={s.grid}>{items.map((asset,index)=>{const chosen=selected.has(asset.id);return <Pressable key={asset.id} style={[s.tile,chosen&&s.selectedTile]} onPress={()=>addTargetAlbumId||selected.size?toggleSelect(asset.id):setViewer(asset)} onLongPress={()=>toggleSelect(asset.id)}><Image source={imageSource(asset)} style={s.photo} contentFit=\"cover\" transition={120}/>{asset.mediaType==='video'&&<View style={s.videoBadge}><Text style={s.videoText}>▶ {asset.duration?formatDuration(asset.duration):''}</Text></View>}{(asset.cloudOnly||syncedIds.has(asset.id))&&index<4&&<View style={s.cloudBadge}><Text style={s.cloudText}>✓</Text></View>}{trashMode&&<View style={s.trashBadge}><Text style={s.trashBadgeText}>Trash</Text></View>}{chosen&&<View style={s.check}><Text style={s.checkText}>✓</Text></View>}</Pressable>;})}</View>; }"
if old not in s:
    old="  function renderGrid(items:DisplayAsset[],trashMode=false){return <View style={s.grid}>{items.map((asset,index)=>{const chosen=selected.has(asset.id);return <Pressable key={asset.id} style={[s.tile,chosen&&s.selectedTile]} onPress={()=>addTargetAlbumId||selected.size?toggleSelect(asset.id):setViewer(asset)} onLongPress={()=>toggleSelect(asset.id)}><Image source={imageSource(asset)} style={s.photo} contentFit=\"cover\" transition={120}/>{asset.mediaType==='video'&&<View style={s.videoBadge}><Text style={s.videoText}>▶ {asset.duration?formatDuration(asset.duration):''}</Text></View>}{(asset.cloudOnly||syncedIds.has(asset.id))&&index<4&&<View style={s.cloudBadge}><Text style={s.cloudText}>✓</Text></View>}{trashMode&&<View style={s.trashBadge}><Text style={s.trashBadgeText}>Trash</Text></View>}{chosen&&<View style={s.check}><Text style={s.checkText}>✓</Text></View>}</Pressable>;})}</View>; }"
# actual source has no space before closing brace
if old not in s:
    old="  function renderGrid(items:DisplayAsset[],trashMode=false){return <View style={s.grid}>{items.map((asset,index)=>{const chosen=selected.has(asset.id);return <Pressable key={asset.id} style={[s.tile,chosen&&s.selectedTile]} onPress={()=>addTargetAlbumId||selected.size?toggleSelect(asset.id):setViewer(asset)} onLongPress={()=>toggleSelect(asset.id)}><Image source={imageSource(asset)} style={s.photo} contentFit=\"cover\" transition={120}/>{asset.mediaType==='video'&&<View style={s.videoBadge}><Text style={s.videoText}>▶ {asset.duration?formatDuration(asset.duration):''}</Text></View>}{(asset.cloudOnly||syncedIds.has(asset.id))&&index<4&&<View style={s.cloudBadge}><Text style={s.cloudText}>✓</Text></View>}{trashMode&&<View style={s.trashBadge}><Text style={s.trashBadgeText}>Trash</Text></View>}{chosen&&<View style={s.check}><Text style={s.checkText}>✓</Text></View>}</Pressable>;})}</View>;}"
if old not in s: raise SystemExit('renderGrid anchor missing')
new="""  function renderTile(asset:DisplayAsset,index:number,trashMode=false){const chosen=selected.has(asset.id);return <Pressable key={asset.id} style={[s.tile,chosen&&s.selectedTile]} onPress={()=>addTargetAlbumId||selected.size?toggleSelect(asset.id):setViewer(asset)} onLongPress={()=>toggleSelect(asset.id)}><Image source={imageSource(asset)} style={s.photo} contentFit=\"cover\" transition={120}/>{asset.mediaType==='video'&&<View style={s.videoBadge}><Text style={s.videoText}>▶ {asset.duration?formatDuration(asset.duration):''}</Text></View>}{(asset.cloudOnly||syncedIds.has(asset.id))&&index<4&&<View style={s.cloudBadge}><Text style={s.cloudText}>✓</Text></View>}{trashMode&&<View style={s.trashBadge}><Text style={s.trashBadgeText}>Trash</Text></View>}{chosen&&<View style={s.check}><Text style={s.checkText}>✓</Text></View>}</Pressable>;}
  function renderGrid(items:DisplayAsset[],trashMode=false){return <View style={s.grid}>{items.map((asset,index)=>renderTile(asset,index,trashMode))}</View>;}
"""
s=s.replace(old,new,1)
old_photos="{tab==='photos'&&<ScrollView contentContainerStyle={s.scrollBottom}><Pressable style={s.backupChip} onPress={()=>setSheet('backup')}><Icon name={failedCount?'warning':pendingCount?'cloudUpload':'cloudDone'} size={18} color={BLUE}/><Text style={s.backupText}>{backupLabel}</Text><Text style={s.backupPercent}>{percent}%</Text></Pressable><View style={s.sectionHead}><Text style={s.sectionTitle}>{addTargetAlbum?'Chọn ảnh để thêm':'Thư viện'}</Text>{!addTargetAlbum&&<Pressable onPress={()=>setSelected(new Set(visiblePhotos.map(x=>x.id)))}><Text style={s.link}>Chọn</Text></Pressable>}</View>{visiblePhotos.length?renderGrid(visiblePhotos):<Empty title=\"Chưa có ảnh\" body=\"Ảnh và video trên thiết bị sẽ xuất hiện ở đây.\"/>}</ScrollView>}"
new_photos="{tab==='photos'&&<View style={s.flex}><Pressable style={s.backupChip} onPress={()=>setSheet('backup')}><Icon name={failedCount?'warning':pendingCount?'cloudUpload':'cloudDone'} size={18} color={BLUE}/><Text style={s.backupText}>{backupLabel}</Text><Text style={s.backupPercent}>{percent}%</Text></Pressable><View style={s.sectionHead}><Text style={s.sectionTitle}>{addTargetAlbum?'Chọn ảnh để thêm':'Thư viện'}</Text>{!addTargetAlbum&&<Pressable onPress={()=>setSelected(new Set(visiblePhotos.map(x=>x.id)))}><Text style={s.link}>Chọn</Text></Pressable>}</View>{visiblePhotos.length?<PhotoTimeline items={visiblePhotos} columns={COLUMNS} renderTile={(asset,index)=>renderTile(asset,index)}/>:<Empty title=\"Chưa có ảnh\" body=\"Ảnh và video trên thiết bị sẽ xuất hiện ở đây.\"/>}</View>}"
if old_photos not in s: raise SystemExit('photos tab anchor missing')
s=s.replace(old_photos,new_photos,1)
p.write_text(s)
