export interface CatalogSnapshot{schemaVersion:1;createdAt:string;catalogVersion:string;payload:Uint8Array;checksum:string;encrypted:boolean;metadata?:Record<string,unknown>;}
export interface CatalogSerializer{export():Promise<{catalogVersion:string;payload:Uint8Array}>;import(payload:Uint8Array):Promise<void>;}
export interface CatalogCrypto{encrypt(data:Uint8Array):Promise<Uint8Array>;decrypt(data:Uint8Array):Promise<Uint8Array>;}
export interface CatalogHasher{sha256(data:Uint8Array):Promise<string>;}
export interface CatalogBackupTarget{id:string;providerId:string;accountId:string;put(snapshot:CatalogSnapshot):Promise<{remoteFileId:string}>;getLatest():Promise<CatalogSnapshot|null>;}
export interface CatalogBackupRecord{targetId:string;providerId:string;accountId:string;remoteFileId?:string;createdAt:string;checksum:string;ok:boolean;message?:string;}
export class CatalogBackupService{
 constructor(private readonly serializer:CatalogSerializer,private readonly hasher:CatalogHasher,private readonly targets:CatalogBackupTarget[],private readonly crypto?:CatalogCrypto){}
 async backup(options:{encrypt?:boolean;minimumSuccessfulTargets?:number}={}):Promise<CatalogBackupRecord[]>{const exported=await this.serializer.export();let payload=exported.payload;let encrypted=false;if(options.encrypt){if(!this.crypto)throw new Error('CATALOG_CRYPTO_NOT_CONFIGURED');payload=await this.crypto.encrypt(payload);encrypted=true;}const checksum=await this.hasher.sha256(payload);const snapshot:CatalogSnapshot={schemaVersion:1,createdAt:new Date().toISOString(),catalogVersion:exported.catalogVersion,payload,checksum,encrypted};const records:CatalogBackupRecord[]=[];for(const target of this.targets){try{const stored=await target.put(snapshot);records.push({targetId:target.id,providerId:target.providerId,accountId:target.accountId,remoteFileId:stored.remoteFileId,createdAt:snapshot.createdAt,checksum,ok:true});}catch(e){records.push({targetId:target.id,providerId:target.providerId,accountId:target.accountId,createdAt:snapshot.createdAt,checksum,ok:false,message:e instanceof Error?e.message:String(e)});}}const minimum=options.minimumSuccessfulTargets??2;if(records.filter(x=>x.ok).length<minimum)throw new Error(`CATALOG_BACKUP_REDUNDANCY_NOT_MET:${records.filter(x=>x.ok).length}/${minimum}`);return records;}
}
export class CatalogRecoveryService{
 constructor(private readonly serializer:CatalogSerializer,private readonly hasher:CatalogHasher,private readonly crypto?:CatalogCrypto){}
 async restore(snapshot:CatalogSnapshot){const actual=await this.hasher.sha256(snapshot.payload);if(actual.toLowerCase()!==snapshot.checksum.toLowerCase())throw new Error('CATALOG_SNAPSHOT_CHECKSUM_MISMATCH');let payload=snapshot.payload;if(snapshot.encrypted){if(!this.crypto)throw new Error('CATALOG_CRYPTO_NOT_CONFIGURED');payload=await this.crypto.decrypt(payload);}await this.serializer.import(payload);return{restoredAt:new Date().toISOString(),catalogVersion:snapshot.catalogVersion};}
 async chooseLatest(targets:CatalogBackupTarget[]){const snapshots=(await Promise.all(targets.map(t=>t.getLatest()))).filter((x):x is CatalogSnapshot=>Boolean(x));return snapshots.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]??null;}
}
