export interface CatalogReplicaRef{assetId:string;providerId:string;accountId:string;remoteFileId:string;state:string;}
export interface ProviderReplicaRef{providerId:string;accountId:string;remoteFileId:string;sizeBytes?:number;checksum?:string;}
export interface ReconciliationCatalog{listReplicas():Promise<CatalogReplicaRef[]>;markMissing(ref:CatalogReplicaRef,message:string):Promise<void>;markVerified(ref:CatalogReplicaRef):Promise<void>;}
export interface ProviderInventory{list(providerId:string,accountId:string):Promise<ProviderReplicaRef[]>;}
export interface RepairScheduler{scheduleRepair(assetId:string,reason:string):Promise<void>;}
export interface ReconciliationIssue{type:'MISSING_REMOTE'|'UNKNOWN_REMOTE'|'STATE_DRIFT';assetId?:string;providerId:string;accountId:string;remoteFileId:string;message:string;}
export interface ReconciliationReport{startedAt:string;finishedAt:string;checkedCatalogReplicas:number;issues:ReconciliationIssue[];repairsScheduled:number;}
export class ReconciliationEngine{
 constructor(private readonly catalog:ReconciliationCatalog,private readonly inventory:ProviderInventory,private readonly repairs?:RepairScheduler){}
 async run():Promise<ReconciliationReport>{const startedAt=new Date().toISOString();const catalogRows=await this.catalog.listReplicas();const groups=new Map<string,CatalogReplicaRef[]>();for(const row of catalogRows){const k=`${row.providerId}:${row.accountId}`;groups.set(k,[...(groups.get(k)??[]),row]);}const issues:ReconciliationIssue[]=[];let repairsScheduled=0;for(const [key,rows] of groups){const [providerId,...rest]=key.split(':');const accountId=rest.join(':');const remote=await this.inventory.list(providerId,accountId);const remoteIds=new Set(remote.map(x=>x.remoteFileId));const catalogIds=new Set(rows.map(x=>x.remoteFileId));for(const row of rows){if(!remoteIds.has(row.remoteFileId)){const issue:ReconciliationIssue={type:'MISSING_REMOTE',assetId:row.assetId,providerId:row.providerId,accountId:row.accountId,remoteFileId:row.remoteFileId,message:'Catalog replica is missing from provider inventory'};issues.push(issue);await this.catalog.markMissing(row,issue.message);if(this.repairs){await this.repairs.scheduleRepair(row.assetId,issue.message);repairsScheduled++;}}else if(row.state!=='VERIFIED'){issues.push({type:'STATE_DRIFT',assetId:row.assetId,providerId:row.providerId,accountId:row.accountId,remoteFileId:row.remoteFileId,message:'Remote object exists but catalog state is not VERIFIED'});await this.catalog.markVerified(row);}}
 for(const r of remote){if(!catalogIds.has(r.remoteFileId))issues.push({type:'UNKNOWN_REMOTE',providerId:r.providerId,accountId:r.accountId,remoteFileId:r.remoteFileId,message:'Provider object is not present in PhotoX catalog'});}}
 return{startedAt,finishedAt:new Date().toISOString(),checkedCatalogReplicas:catalogRows.length,issues,repairsScheduled};}
}
