// @ts-nocheck
import assert from 'node:assert/strict';
import http from 'node:http';
import net from 'node:net';
import test from 'node:test';
import { PhotoXWebEdgeServer } from './webEdgeServer.js';

async function freePort(){const listener=net.createServer();await new Promise((resolve,reject)=>{listener.once('error',reject);listener.listen(0,'127.0.0.1',resolve);});const address=listener.address();if(!address||typeof address==='string')throw new Error('NO_TEST_PORT');await new Promise((resolve,reject)=>listener.close(error=>error?reject(error):resolve()));return address.port;}
function request(port,path,input={}){return new Promise((resolve,reject)=>{const body=input.body===undefined?undefined:Buffer.from(JSON.stringify(input.body));const req=http.request({host:'127.0.0.1',port,path,method:input.method||'GET',headers:body?{'content-type':'application/json','content-length':String(body.length)}:{}},res=>{const chunks=[];res.on('data',chunk=>chunks.push(Buffer.from(chunk)));res.on('end',()=>{const value=Buffer.concat(chunks);resolve({status:res.statusCode||0,headers:res.headers,json:value.length?JSON.parse(value.toString('utf8')):undefined});});});req.once('error',reject);if(body)req.write(body);req.end();});}
const principal={subject:'user-a',workspaceId:'workspace-a',workspaceRole:'owner',deviceId:'web-device',sessionId:'session-one',scopes:['media:read','media:download','media:write','media:delete']};
function handlers(){return {async authorizeAccessToken(){return principal;},async createWebSession(){return {accessToken:'access-one',refreshToken:'refresh-one',accessExpiresAt:Date.now()+60_000,sessionId:'session-one'};},async refreshSession(){return {accessToken:'access-two',accessExpiresAt:Date.now()+60_000,sessionId:'session-one'};},async revokeSession(){},async appendAudit(){},async getStatus(){return {};},async getTunnelStatus(){return {};},async listLocalMedia(){return [];},async listCloudUploads(){return [];},async getBackupHealth(){return {};},async openLibrary(){return {};},async addGoogleAccount(){return {};},async listGoogleAccounts(){return [];},async removeGoogleAccount(){return {};},async retryCloud(){return {};},async listGooglePhotosAccounts(){return [];},async connectGooglePhotosAccount(){return {};},async removeGooglePhotosAccount(){return {};},async listMigrations(){return [];},async getMigration(){return {};},async createMigration(){return {};},async materializeMigration(){return {};},async runMigration(){return {};},async pauseMigration(){return {};},async resumeMigration(){return {};},async cancelMigration(){return {};},async retryMigration(){return {};},async streamMedia(_req,res){res.writeHead(404);res.end();}};}

test('Web login ticket is one-time and installs hardened cookies',async()=>{const port=await freePort();const server=new PhotoXWebEdgeServer({enabled:true,host:'127.0.0.1',port,allowedOrigins:[],staticDir:'.',rateLimitPerMinute:300},handlers());await server.start();try{const issued=await server.issueLoginTicket();const ticket=decodeURIComponent(new URL(issued.url).hash.replace(/^#ticket=/,''));assert.ok(ticket);const login=await request(port,'/api/web/v1/auth/ticket',{method:'POST',body:{ticket}});assert.equal(login.status,200);assert.equal(login.json.accessToken,'access-one');const setCookie=login.headers['set-cookie']||[];assert.ok(setCookie.some(value=>value.startsWith('photox_refresh=')&&value.includes('HttpOnly')&&value.includes('SameSite=Strict')));assert.ok(setCookie.some(value=>value.startsWith('photox_csrf=')&&value.includes('Path=/')));const replay=await request(port,'/api/web/v1/auth/ticket',{method:'POST',body:{ticket}});assert.equal(replay.status,401);}finally{await server.stop();}});
