export type JobState='QUEUED'|'RUNNING'|'PAUSED'|'RETRY_WAIT'|'COMPLETED'|'FAILED'|'CANCELLED';
export interface DurableJob<T=unknown>{id:string;workspaceId:string;type:string;payload:T;state:JobState;priority:number;attempts:number;maxAttempts:number;runAfter?:string;createdAt:string;updatedAt:string;lastError?:string;checkpoint?:Record<string,unknown>;}
export interface JobRepository{put(job:DurableJob):Promise<void>;get(workspaceId:string,id:string):Promise<DurableJob|null>;list(workspaceId:string,states?:JobState[]):Promise<DurableJob[]>;}
const key=(workspaceId:string,id:string)=>`${workspaceId}\u0000${id}`;
export class MemoryJobRepository implements JobRepository{private rows=new Map<string,DurableJob>();async put(j:DurableJob){if(!j.workspaceId)throw new Error('JOB_WORKSPACE_REQUIRED');this.rows.set(key(j.workspaceId,j.id),{...j});}async get(workspaceId:string,id:string){return this.rows.get(key(workspaceId,id))??null;}async list(workspaceId:string,states?:JobState[]){return [...this.rows.values()].filter(j=>j.workspaceId===workspaceId&&(!states||states.includes(j.state)));}}
export interface JobContext{checkpoint(data:Record<string,unknown>):Promise<void>;isCancelled():Promise<boolean>;}
export type JobHandler<T=unknown>=(payload:T,ctx:JobContext)=>Promise<void>;
export class DurableJobQueue{
 private handlers=new Map<string,JobHandler>();
 constructor(private readonly repo:JobRepository,private readonly workspaceId:string,private readonly now=()=>new Date()){if(!workspaceId)throw new Error('JOB_WORKSPACE_REQUIRED');}
 register<T>(type:string,handler:JobHandler<T>){this.handlers.set(type,handler as JobHandler);return this;}
 async enqueue<T>(type:string,payload:T,options:{priority?:number;maxAttempts?:number;runAfter?:string}={}){const t=this.now().toISOString();const job:DurableJob<T>={id:`job_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,workspaceId:this.workspaceId,type,payload,state:'QUEUED',priority:options.priority??0,attempts:0,maxAttempts:options.maxAttempts??5,runAfter:options.runAfter,createdAt:t,updatedAt:t};await this.repo.put(job);return job;}
 async next(){const now=this.now().toISOString();const jobs=await this.repo.list(this.workspaceId,['QUEUED','RETRY_WAIT']);return jobs.filter(j=>!j.runAfter||j.runAfter<=now).sort((a,b)=>b.priority-a.priority||a.createdAt.localeCompare(b.createdAt))[0]??null;}
 async runNext(){const job=await this.next();if(!job)return null;const handler=this.handlers.get(job.type);if(!handler)throw new Error(`JOB_HANDLER_NOT_REGISTERED:${job.type}`);job.state='RUNNING';job.attempts++;job.updatedAt=this.now().toISOString();await this.repo.put(job);const ctx:JobContext={checkpoint:async data=>{job.checkpoint={...(job.checkpoint??{}),...data};job.updatedAt=this.now().toISOString();await this.repo.put(job);},isCancelled:async()=>((await this.repo.get(this.workspaceId,job.id))?.state==='CANCELLED')};try{await handler(job.payload,ctx);if((await this.repo.get(this.workspaceId,job.id))?.state!=='CANCELLED')job.state='COMPLETED';job.lastError=undefined;}catch(e){job.lastError=e instanceof Error?e.message:String(e);job.state=job.attempts>=job.maxAttempts?'FAILED':'RETRY_WAIT';if(job.state==='RETRY_WAIT')job.runAfter=new Date(this.now().getTime()+Math.min(3600000,1000*2**job.attempts)).toISOString();}job.updatedAt=this.now().toISOString();await this.repo.put(job);return job;}
 async cancel(id:string){const j=await this.repo.get(this.workspaceId,id);if(j){j.state='CANCELLED';j.updatedAt=this.now().toISOString();await this.repo.put(j);}}
 async pause(id:string){const j=await this.repo.get(this.workspaceId,id);if(j){j.state='PAUSED';j.updatedAt=this.now().toISOString();await this.repo.put(j);}}
 async resume(id:string){const j=await this.repo.get(this.workspaceId,id);if(j&&j.state==='PAUSED'){j.state='QUEUED';j.updatedAt=this.now().toISOString();await this.repo.put(j);}}
}
