export type MediaKind='image'|'video'|'live-photo'|'unknown';
export interface PolicyContext{assetId:string;mediaType:MediaKind;sizeBytes:number;albumIds?:string[];favorite?:boolean;important?:boolean;edited?:boolean;}
export interface ReplicaPolicyRule{ id:string; priority:number; when?:{mediaTypes?:MediaKind[];minSizeBytes?:number;maxSizeBytes?:number;albumIds?:string[];favorite?:boolean;important?:boolean;edited?:boolean}; targetReplicas:number; minimumDistinctAccounts?:number; minimumDistinctProviders?:number; allowProviders?:string[]; denyProviders?:string[]; requireOriginal?:boolean; backupEditRecipe?:boolean; backupRenderedCopy?:boolean; }
export interface ResolvedReplicaPolicy{ruleId:string;targetReplicas:number;minimumDistinctAccounts:number;minimumDistinctProviders:number;allowProviders?:string[];denyProviders?:string[];requireOriginal:boolean;backupEditRecipe:boolean;backupRenderedCopy:boolean;}
function matches(ctx:PolicyContext,rule:ReplicaPolicyRule){const w=rule.when;if(!w)return true;if(w.mediaTypes&&!w.mediaTypes.includes(ctx.mediaType))return false;if(w.minSizeBytes!==undefined&&ctx.sizeBytes<w.minSizeBytes)return false;if(w.maxSizeBytes!==undefined&&ctx.sizeBytes>w.maxSizeBytes)return false;if(w.favorite!==undefined&&ctx.favorite!==w.favorite)return false;if(w.important!==undefined&&ctx.important!==w.important)return false;if(w.edited!==undefined&&ctx.edited!==w.edited)return false;if(w.albumIds&&!(ctx.albumIds??[]).some(x=>w.albumIds!.includes(x)))return false;return true;}
export class AdvancedReplicaPolicyEngine{constructor(private readonly rules:ReplicaPolicyRule[],private readonly fallback:ResolvedReplicaPolicy={ruleId:'default',targetReplicas:2,minimumDistinctAccounts:2,minimumDistinctProviders:1,requireOriginal:true,backupEditRecipe:true,backupRenderedCopy:false}){}resolve(ctx:PolicyContext):ResolvedReplicaPolicy{const r=[...this.rules].sort((a,b)=>b.priority-a.priority).find(x=>matches(ctx,x));if(!r)return this.fallback;return{ruleId:r.id,targetReplicas:r.targetReplicas,minimumDistinctAccounts:r.minimumDistinctAccounts??Math.min(2,r.targetReplicas),minimumDistinctProviders:r.minimumDistinctProviders??1,allowProviders:r.allowProviders,denyProviders:r.denyProviders,requireOriginal:r.requireOriginal??true,backupEditRecipe:r.backupEditRecipe??true,backupRenderedCopy:r.backupRenderedCopy??false};}}
export interface ProviderCandidate{providerId:string;accountId:string;status:'ready'|'unavailable'|'full'|'auth_required';freeBytes?:number;latencyMs?:number;recentFailureRate?:number;maxObjectSizeBytes?:number;existingProviderUsed?:boolean;existingAccountUsed?:boolean;}
export interface CandidateScore{providerId:string;accountId:string;score:number;eligible:boolean;reasons:string[];}
export class ProviderScoringEngine{score(ctx:PolicyContext,policy:ResolvedReplicaPolicy,c:ProviderCandidate):CandidateScore{const reasons:string[]=[];if(c.status!=='ready')reasons.push(`status:${c.status}`);if(policy.allowProviders&&!policy.allowProviders.includes(c.providerId))reasons.push('provider-not-allowed');if(policy.denyProviders?.includes(c.providerId))reasons.push('provider-denied');if(c.maxObjectSizeBytes!==undefined&&ctx.sizeBytes>c.maxObjectSizeBytes)reasons.push('object-too-large');if(c.freeBytes!==undefined&&c.freeBytes<ctx.sizeBytes)reasons.push('insufficient-space');if(reasons.length)return{providerId:c.providerId,accountId:c.accountId,score:0,eligible:false,reasons};let score=1000;if(c.freeBytes)score+=Math.min(300,Math.log10(Math.max(1,c.freeBytes))*20);if(c.latencyMs!==undefined)score-=Math.min(200,c.latencyMs/5);if(c.recentFailureRate!==undefined)score-=Math.min(400,c.recentFailureRate*400);if(c.existingAccountUsed)score-=250;if(c.existingProviderUsed)score-=100;return{providerId:c.providerId,accountId:c.accountId,score,eligible:true,reasons:[]};}rank(ctx:PolicyContext,policy:ResolvedReplicaPolicy,candidates:ProviderCandidate[]){return candidates.map(c=>this.score(ctx,policy,c)).filter(x=>x.eligible).sort((a,b)=>b.score-a.score);}}
export const DEFAULT_PHOTOX_RULES:ReplicaPolicyRule[]=[{id:'important',priority:100,when:{important:true},targetReplicas:3,minimumDistinctAccounts:3,minimumDistinctProviders:2,requireOriginal:true,backupEditRecipe:true,backupRenderedCopy:true},{id:'large-video',priority:80,when:{mediaTypes:['video'],minSizeBytes:50*1024*1024},targetReplicas:2,minimumDistinctAccounts:2,minimumDistinctProviders:1,denyProviders:['telegram-bot'],requireOriginal:true,backupEditRecipe:false,backupRenderedCopy:false},{id:'edited',priority:60,when:{edited:true},targetReplicas:2,minimumDistinctAccounts:2,minimumDistinctProviders:1,requireOriginal:true,backupEditRecipe:true,backupRenderedCopy:false},{id:'default',priority:0,targetReplicas:2,minimumDistinctAccounts:2,minimumDistinctProviders:1,requireOriginal:true,backupEditRecipe:true,backupRenderedCopy:false}];
